config/routes.rb
Toomanychips::Application.routes.draw do

  get 'auth/:provider/callback', to: 'session#oauth_create'
  get 'auth/failure', to: redirect('/')
  post 'auth/failure', to: redirect('/')
  delete 'signout', to: 'session#destroy', via: :destroy
  root to: 'pages#index'
  resources :users, :only => [:show, :create, :new, :edit, :guest_create, :update] 
  resources :event_items, :only => [:destroy] 
  post 'create_guest' => 'users#create_guest'
  post 'create_guest' => 'users#create_guest'
  resources :assigned_items, :except => [:index]
  delete 'remove/:id', to: 'assigned_items#destroy', as: 'remove'
  get 'add_image/:id', to: "events#add_image", as: 'add_image'
  post 'update_all_items/:id' =>'events#update_all_items'
  get 'your_profile', to: 'users#your_profile', as: 'your_profile'
  resources :session, :only => [:create]
  get 'login'  => 'users#simple_login', :as => 'login'
  post 'login' => 'session#create'
  get 'guest/:url' => 'users#guest', as: 'guest'

  resources :events
  get 'event/:url' => 'events#invitation', :as => 'invitation'
  get '/contributions/:id' => 'events#contributions', :as => 'contributions'

  resources :items
  
  
  resources :guests, :only => [:show, :edit, :new, :create]
  get '/rsvp/:url' => 'guests#show', :as => 'rsvp'

  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/user.rb
class User < ActiveRecord::Base
  require 'bcrypt'
  include ActiveModel::SecurePassword::InstanceMethodsOnActivation
  attr_reader :password #allow user to be guest ot registered

  validates_presence_of :name, :email
  validates :email, :uniqueness => {:case_sensitive => false, :message => "has already been registered"}, 
  :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, 
  :message => "must be a valid format" }
  validates :password, :length => {:minimum => 6, :too_short  => "must have at least 6 characters"}, unless: :guest? 
  validates_confirmation_of :password
  has_many :assigned_items, :dependent => :destroy
  has_many :event_items, :through => :assigned_items
  has_many :events
  has_many :assigned_items, :class_name => 'AssignedItem', :foreign_key => 'user_id'
  belongs_to :event, :class_name => 'User', foreign_key: 'user_id'
  accepts_nested_attributes_for :assigned_items, :event_items
  has_many :sent_messages, :class_name => 'Message', :foreign_key => 'sender_id'
  has_many :recieved_messaged, :class_name => 'Message', :foreign_key => 'reciepientId'

  # after_save :registration_emails!
  before_create :set_url
  
  def get_contributions(id)
    self.assigned_items.select { |item| item if (item.event_id == id) }
  end

  def duplicate_item?(item)
    return !self.assigned_items.find_by_event_item_id(item["id"]).nil?
  end

  def add_items(items)
    items.each do |item|
      if self.duplicate_item?(item)
        existing_item = self.assigned_items.find_by_event_item_id(item["id"])
        existing_item.quantity_provided = (existing_item.quantity_provided + item["amountToBring"].to_i)
        existing_item.save!
      else
        self.assigned_items << AssignedItem.new(quantity_provided: item["amountToBring"].to_i, 
          event_item_id: item["id"], event_id: item["eventId"])
        self.save!
      end
    end
  end

  private

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      p user.errors.full_messages
      user.password = auth.credentials.expires_at.to_s if user.password.nil?
      user.save!
    end
  end

  def set_url
    self.url ||= SecureRandom.urlsafe_base64 if self.guest
  end

  def registration_emails!
    schedule_result_email unless self.result_date == nil
    send_email
  end

  def schedule_result_email
    EmailWorker.perform_at(self.result_date, self.user_id, self.id, 'result')
  end

  def send_email
    EmailWorker.perform_async(self.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json, :html
  before_filter :logged_in?, :only => [:show, :edit, :destroy, :your_profile]
  before_filter :load_and_authorize_user, :only => [:show, :edit, :destroy]

  def your_profile
    @user = current_user
    render :show
  end

  #refactor: put in session controller?
  def simple_login
    @login_error = session[:login_error]
  end

  def create_guest
    email = person_params[:email] || current_user.email
    user = User.find_by_email(email) 
    items = person_params[:items] || []
    if user
      user.add_items(items)
    else
      user = User.new
      user.name = person_params[:name]
      user.email = person_params[:email]
      user.guest = true
      user.save!
      user.add_items(items)
    end 
    if user.save && user.guest
      render :js => "window.location = '/guest/#{user.url}/'"
    elsif 
      render :js => "window.location = '/your_profile/'"
    else 
      #what is this
      user.errors.full_messages
    end
  end

  def create 
    user = User.new(person_params)
    if user.save
      session[:id] = user.id
      redirect_to your_profile_path
    else
      redirect_to login_path
    end 
  end

  #refactor: this probably doesn't work
  def destroy
    @user.destroy
  end

  def update 
    if current_user.nil?
      user = User.find_by_url(person_params[:url])
      user.update(person_params)
      user.guest = false
      user.url = nil
      user.save!
      session[:id] = user.id
      redirect_to your_profile_path
    else
      current_user.update(person_params)
      current_user.save!
      redirect_to your_profile_path
    end
  end

  def guest
    @user = User.find_by_url(params[:url])
    if @user
      render :show
    else 
      redirect_to login_path
    end
  end

  private

  def person_params
    params.require(:user).permit(:name, :email, :guest, :url, :password, :password_confirmation, 
      :items => [:name, :description, :id, :amountPromised, :quantity, :amountToBring, :eventId, :stillNeeded]
      )
  end
end

app/views/users/_guest.html.erb
<% if @user.guest %>
	<p class='center default_label'>To track and edit your contributions please bookmark <a href="toomanychips.com/guest/#{@user.url}", id='createGuestAccount' class="blue_label">this page</a> or  <a href="#" class="blue_label" id='createAccountButton'>create an account.</a></p>


<div class='hide' id='createAccountFromGuest' >
  <fieldset>
    <%= form_for @user do |f| %>
    <div class="row">
      <div class="large-12 columns">
        <label>Your name</label>
        <%= f.text_field :name, :id => "inputName", :required => true, placeholder: "Name" %>
      </div>
    </div>
    <input type="hidden" id="url" name="user[url]" value=<%=@user.url%> />

    <div class="row">
      <div class="large-12 columns">
        <label>A unique password</label>
        <%= f.password_field :password, :id => "inputPassword", :required => true, placeholder: "Password" %>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <label>Confirm your password</label>
        <%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %>
      </div>
    </div>
     <div class="row">
      <div class="large-12 columns">
    <%= f.submit "Sign up", class: 'event_done right' %>
    </div>
    </div>
    <% end %>
  </fieldset>
</div>

<%end%>
<h3 class='subheader'>
<span class='white'>Your Contributions</span>
</h3>
<div class='event-list border_top_white'>
	<%= render 'item' %>
</div>

app/views/users/_item.html.erb
    <% unless @user.assigned_items.length > 0 %>
    <h3 class='subheader center'><span class='grey'> You don't have any contributions.</span></h3>
    <%else%>
    <% @user.assigned_items.each do |item| %>
        <div>
          
        </div>
    <% end %>
  <%end%>


<!--   <tr id="<%= item.id %>">  
      <td><%= item.event_item.item.name %></td>
      <td><%= item.quantity_provided %></td>
      <td><%= item.event_item.description%></td>
      <td> <%= link_to #{}"#{item.event_item.event.name}", event_path(item.event_item.event)%></td>
      <td > <%= link_to #'remove', remove_path(item), class: 'default_button', :method => :delete, :remote => :true,  id: "remove_trigger", "data-type" => :json%></td>
    </tr>   -->

app/views/users/_login_form.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class='facebook-button center'>
      <span><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in"%></span>
    </div>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
   <% flash.each do |name, msg| -%>
   <%= msg %>
   <% end -%>
 </div>
</div>
<div class='login'>
  <fieldset>
    <%= form_tag session_index_path, :class => "login"  do %>
    <div class="row">
      <div class="large-12 columns">
        <span class='errors'> <%= @login_error if @login_error %></span>
        <%= email_field_tag :email, nil, placeholder: "Email" %><br>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= password_field_tag :password, nil, placeholder: "Password" %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= submit_tag "Log In", class: "event_done right" %>
      </div>
    </div>
    <% end %>
  </fieldset>
</div>

<div class='signup'>
  <fieldset>
    <% @user = User.new %>
    <%= form_for @user do |f| %>
    <div class="row">
      <div class="large-12 columns">
        <label>Your name</label>
        <%= f.text_field :name, :id => "inputName", :required => true, placeholder: "Name" %>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <label>Your email address</label>
        <%= f.email_field :email, :id => "inputEmail", :required => true, placeholder: "Email" %>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <label>A unique password</label>
        <%= f.password_field :password, :id => "inputPassword", :required => true, placeholder: "Password" %>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <label>Confirm your password</label>
        <%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <%= f.submit "Sign up", class: 'event_done right' %>
      </div>
    </div>
    <% end %>
  </fieldset>
</div>

app/views/users/_show_events.html.erb
<button class='default_button'>
  <%= link_to "Create A New Event",  new_event_path%>
</button>
<h3 class='subheader'><span class='white'>Your Upcoming Events</span></h3>
<div class='event-list dark'>

  <% if current_user.events.length >= 1 %>
  <table class='user-show default_table'>
    
    <tbody>
      <% current_user.events.each do |event| %>
      <tr> <td> <%= link_to event.name.titleize, event_path(event) %></td><td> <%= event.date %></td>
        <td>www.toomanychips.com/<%= event.url %> </td> <td><%= link_to 'Edit |', edit_event_path(event)%>
        <%= link_to 'View Guests', contributions_path(event)%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%else%>

  <h3 class='subheader center'> <span class='white'>You don't have any upcoming events.</span></h3>
  <% end %>


 <h3 class="subheader"><span class='white'>Your Past Events</span></h3>

 <div class='notifcations large-12 columns border_top_white'>
   <h3 class="subheader center"><span class='white'>You don't have any past events.</span></h3>
 </div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'signup_form' %>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class='large-12 wrapper columns dark'>
  <div class='row'>
    <div class='large-12 user-show columns'>

      <% if current_user %>
      <%= render 'show_events' %>
            <%end%>

      <%= render 'guest' %>
      

    </div>
  </div>
</div>

app/views/users/simple_login.html.erb
<%= render "users/login_form.html" %>

app/views/users/~_guest.html.erb
<h3 class='subheader'><span class='grey'>Your Contributions</span></h3>
<div class='event-list border-top'>
<br>
<% if @user.guest %>
	<p class='center'>To edit your contributions please bookmark this page: 
	<%=link_to "toomanychips.com/guest/#{@user.url}", guest_path(@user.url)%>
	<%end%>
	<table class='user-show'>
		<% unless @user.assigned_items.length > 0 %>
		<h3 class='subheader center'><span class='grey'> You don't have any contributions.</span></h3>
		<%else%>
		<% @user.assigned_items.each do |item| %>
		<tr id="<%= item.id %>">  
			<td><%= item.event_item.item.name %></td>
			<td><%= item.quantity_provided %></td>
			<td><%= item.event_item.description%></td>
			<td> <%= link_to "#{item.event_item.event.name}", event_path(item.event_item.event)%></td>
			<td> <%= link_to 'remove', remove_path(item), class: 'remove_fields', :method => :delete, :remote => :true,  id: "remove_trigger", "data-type" => :json , :confirm => 'Are you sure?'%></td>
		</tr>  
		<% end %>
	</table>
	<%end%>
</div>