config/routes.rb
Toomanychips::Application.routes.draw do

  get 'auth/:provider/callback', to: 'session#oauth_create'
  get 'auth/failure', to: redirect('/')
  post 'auth/failure', to: redirect('/')
  delete 'signout', to: 'session#destroy', via: :destroy
  root to: 'pages#index'
  resources :users, :only => [:show, :create, :new, :edit, :guest_create, :update] 
  resources :event_items, :only => [:destroy] 
  post 'create_guest' => 'users#create_guest'
  post 'create_guest' => 'users#create_guest'
  resources :assigned_items, :except => [:index]
  delete 'remove/:id', to: 'assigned_items#destroy', as: 'remove'
  get 'add_image/:id', to: "events#add_image", as: 'add_image'
  post 'update_all_items/:id' =>'events#update_all_items'
  get 'your_profile', to: 'users#your_profile', as: 'your_profile'
  resources :session, :only => [:create]
  get 'login'  => 'users#simple_login', :as => 'login'
  post 'login' => 'session#create'
  get 'guest/:url' => 'users#guest', as: 'guest'

  resources :events
  get 'event/:url' => 'events#invitation', :as => 'invitation'
  get '/contributions/:id' => 'events#contributions', :as => 'contributions'

  resources :items
  
  
  resources :guests, :only => [:show, :edit, :new, :create]
  get '/rsvp/:url' => 'guests#show', :as => 'rsvp'

  mount Sidekiq::Web, at: "/sidekiq"

end

app/views/layouts/_nav.html.erb
<nav class="top-bar">

  <ul class="title-area">
    <li class="named">
      <!-- <img src="/assets/100_red_copy.png"> --><a class'logo' 
      <% if current_user%>
      href="/your_profile">
      <%else%>
      href="/">
      <%end%>
      TOO<strong>MANY</strong>CHIPS</a>
    </li>
     <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="left">
    </ul>
    <ul class="right">
      <% if current_user %>
<!--       <li><a href='/' >Create New Event<a/></li>
 -->      <li><%= link_to "Sign Out", signout_path, method: :delete %></li>
      <%else%>
      <li><a data-reveal-id="signIn" href="#">Log In Sign Up</a></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
 <meta charset="utf-8" />
 <%= csrf_meta_tags %>
 <!-- Uncomment to make IE8 render like IE7 -->
 <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
<link rel="shortcut icon" href="/assets/104_white.png"/>
 <!-- Set the viewport width to device width for mobile -->
 <meta name="viewport" content="width=device-width, initial-scale=1.0" />

 <title><%= content_for?(:title) ? yield(:title) : "TooManyChips" %></title>
 <%= render "layouts/nav" %>
 <link href='http://fonts.googleapis.com/css?family=Tienne' rel='stylesheet' type='text/css'>
 <%= stylesheet_link_tag    "application" %>
 <%= javascript_include_tag "vendor/custom.modernizr" %>
 <%= csrf_meta_tags %>

</head>

<body>

  <%= yield %>

  <%= javascript_include_tag "application" %>
  <div id="signIn" class="reveal-modal medium">
    <%= render 'users/login_form' %>
  </div>

</body>

</html>